# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
#
# conda env create --file environment.yaml
#
# Update the conda environment:
#
# conda env update --file environment.yaml
#
# Activate the conda environment:
#
# source activate bulkRNAseq
#
# Deactivate the conda environment:
#
# source deactivate bulkRNAseq
#
# Resources:


name:
    bulkRNAseq
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python
    - fastqc
    - snakemake
    - STAR >=2.7.3a-0
    - subread
    - cutadapt
    - samtools
    - multiqc
    - ucsc-gtftogenepred
